### ISSUE TITLE
AssertionError: Default process group is not initialized

### ISSUE THREAD

**Issue by Rajrup** [Media-Smart/vedaseg#33]
I am trying to train using "python tools/train.py configs/voc_unet.py"
I get an error saying **AssertionError: Default process group is not initialized**
Can you please help me resolve this? Do I need to change anything in the config file?

Traceback (most recent call last):
  File "tools/train.py", line 47, in <module>
    main()
  File "tools/train.py", line 42, in main
    runner = TrainRunner(train_cfg, inference_cfg, common_cfg)
  File "tools/../vedaseg/runner/train_runner.py", line 20, in __init__
    train_cfg['data']['train'])
  File "tools/../vedaseg/runner/base.py", line 91, in _build_dataloader
    'sampler') is not None else None
  File "tools/../vedaseg/dataloaders/samplers/builder.py", line 6, in build_sampler
    sampler = build_from_cfg(cfg, SAMPLERS, default_args)
  File "tools/../vedaseg/utils/registry.py", line 50, in build_from_cfg
    return build_from_registry(cfg,  src, default_args=default_args)
  File "tools/../vedaseg/utils/registry.py", line 83, in build_from_registry
    return obj_cls(**args)
  File "/home/rajrup/miniconda3/envs/vedaseg/lib/python3.7/site-packages/torch/utils/data/distributed.py", line 43, in __init__
    num_replicas = dist.get_world_size()
  File "/home/rajrup/miniconda3/envs/vedaseg/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 582, in get_world_size
    return _get_group_size(group)
  File "/home/rajrup/miniconda3/envs/vedaseg/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 196, in _get_group_size
    _check_default_pg()
  File "/home/rajrup/miniconda3/envs/vedaseg/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 187, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized

**Comment by YuxinZou** [comment]
Hi @Rajrup ,
Thanks for your interest in our VedaSeg.
The default config file is set for distributed training, if you want to use non-distributed training, you need to **uncomment sampler part in config file**.

**Comment by Rajrup** [comment]
Thanks a lot!
It worked for me :)
