### ISSUE TITLE
Validating Problem

### ISSUE THREAD

**Issue by lun-lun-byte** [Media-Smart/vedaseg#54]
Hello, I am testing the model, but it shows . How can I fix this? Thanks

`2021-08-15 16:53:59,781 - INFO - Start validating
Traceback (most recent call last):
  File "tools/train.py", line 47, in <module>
    main()
  File "tools/train.py", line 43, in main
    runner()
  File "tools/../vedaseg/runners/train_runner.py", line 148, in __call__
    res = self._val()
  File "tools/../vedaseg/runners/train_runner.py", line 111, in _val
    for idx, (image, mask) in enumerate(self.val_dataloader):
  File "/root/anaconda3/envs/vedaseg/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/vedaseg/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 838, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/vedaseg/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/vedaseg/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/vedaseg/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/vedaseg/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/root/anaconda3/envs/vedaseg/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/root/anaconda3/envs/vedaseg/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/root/anaconda3/envs/vedaseg/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 641 and 691 in dimension 2 at /pytorch/aten/src/TH/generic/THTensor.cpp:612
`

**Comment by lun-lun-byte** [comment]
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 641 and 691 in dimension 2 at /pytorch/aten/src/TH/generic/THTensor.cpp:612
