### ISSUE TITLE
AttributeError: 'SyncBatchNorm' object has no attribute '_specify_ddp_gpu_num'

### ISSUE THREAD

**Issue by CamelKing1997** [Media-Smart/vedaseg#55]
How can i slove this problem?

(vedaseg) E:\00_Public_Project\vedaseg>python tools/train.py configs/voc_deeplabv3plus.py
2021-09-13 14:58:24,709 - INFO - Set cudnn deterministic False
2021-09-13 14:58:24,710 - INFO - Set cudnn benchmark True
2021-09-13 14:58:24,710 - INFO - Set seed 0
2021-09-13 14:58:24,711 - INFO - Build model
Traceback (most recent call last):
  File "tools/train.py", line 47, in <module>
    main()
  File "tools/train.py", line 42, in main
    runner = TrainRunner(train_cfg, inference_cfg, common_cfg)
  File "tools\..\vedaseg\runners\train_runner.py", line 16, in __init__
    super().__init__(inference_cfg, base_cfg)
  File "tools\..\vedaseg\runners\inference_runner.py", line 21, in __init__
    self.model = self._build_model(inference_cfg['model'])
  File "tools\..\vedaseg\runners\inference_runner.py", line 39, in _build_model
    model = build_model(cfg)
  File "tools\..\vedaseg\models\builder.py", line 10, in build_model
    encoder = build_encoder(cfg.get('encoder'))
  File "tools\..\vedaseg\models\encoders\builder.py", line 9, in build_encoder
    backbone = build_from_cfg(cfg['backbone'], BACKBONES, default_args)
  File "tools\..\vedaseg\utils\registry.py", line 51, in build_from_cfg
    return build_from_registry(cfg,  src, default_args=default_args)
  File "tools\..\vedaseg\utils\registry.py", line 84, in build_from_registry
    return obj_cls(**args)
  File "tools\..\vedaseg\models\encoders\backbones\resnet.py", line 315, in __init__
    act_cfg=act_cfg)
  File "tools\..\vedaseg\models\encoders\backbones\resnet.py", line 181, in __init__
    self._make_stem_layer()
  File "tools\..\vedaseg\models\encoders\backbones\resnet.py", line 270, in _make_stem_layer
    self.bn1 = self._norm_layer(self.inplanes)
  File "tools\..\vedaseg\models\utils\norm.py", line 81, in build_norm_layer
    layer._specify_ddp_gpu_num(1)  # noqa
  File "C:\ProgramData\Anaconda3\envs\vedaseg\lib\site-packages\torch\nn\modules\module.py", line 1131, in __getattr__
    type(self).__name__, name))
AttributeError: 'SyncBatchNorm' object has no attribute '_specify_ddp_gpu_num'

**Comment by DarthThomas** [comment]
Hi,

Thanks for your interest in our VedaSeg.

Based on the information you provided, it's likely that you are using a newer version of Pytorch.
The method `_specify_ddp_gpu_num` is no longer there in the latest version of Pytorch and that's the reason you are getting this AttributeError.

To resolve this problem, I recommend you try PyTorch 1.4.0. 

Also, it seems that you are using Windows, we recommend using Linux instead.

**Comment by CamelKing1997** [comment]
Thx. I will try PyTorch 1.4.0.

**Comment by panovr** [comment]
It seems `_specify_ddp_gpu_num()` is no longer available after PyTorch 1.9.0. I have tried PyTorch 1.8.2, and it worked.
https://github.com/open-mmlab/mmocr/issues/325
https://github.com/open-mmlab/mmcv/issues/1137
